dist: bionic

language: ruby
cache: bundler

services:
  - mysql
  - postgresql

env:
  - DB=mysql
  - DB=postgres

rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8

gemfile:
  - gemfiles/spree_4.0.gemfile
  - gemfiles/spree_4.1.gemfile
  - gemfiles/spree_master.gemfile

script:
  - bundle exec rake test_app
  - bundle exec rake spec
